language: cpp
compiler: gcc

script:
- cd test
- g++ -Wall -fexceptions -O2 -std=c++11  -c ../sha256.cpp -o sha256.o
- g++ -Wall -fexceptions -O2 -std=c++11  -c main.cpp -o main.o
- g++ -o travis_test sha256.o main.o -s
- ./travis_test
